### ISSUE TITLE
move检测导致了一点点的滞后

### ISSUE THREAD

**Issue by ghost** [Ez4p1xEL/NoBuildPlus#1]
![image](https://user-images.githubusercontent.com/87688330/211021679-0184f3ad-b398-4b63-8a83-e78023b5b29d.png)
在spark检测里nobuildplus的这项过于滞后，而且我并没有在任何世界开启阻止移动

**Comment by justLxy** [comment]
同！！！拉低了服务器TPS

**Comment by Ez4p1xEL** [comment]
尝试一下1.2.6版本

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/87688330/211240934-5fcf9c3b-21be-4f31-bebd-501686ad839f.png)
有变化，当时依旧是最滞后的

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/87688330/211241077-fa6b805e-b45d-4a4d-af1a-6834f54252fc.png)
确定我没有在任何世界阻止move

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/87688330/211241134-fae98b3f-0212-42e4-972f-034b50718b92.png)

**Comment by Ez4p1xEL** [comment]
你的flags.yml里的move也是关闭的吗

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/87688330/211268674-8ecfd381-ed4e-4c65-8eb1-37394b2d96ef.png)
是的

**Comment by Ez4p1xEL** [comment]
我可能得删掉这个规则

**Comment by postyizhan** [comment]
![图片](https://github.com/Ez4p1xEL/NoBuildPlus/assets/97342038/653abfe9-dbda-4314-89bb-f61c90f81243)
怎么想

**Comment by Ez4p1xEL** [comment]
可以尝试新版本
