### ISSUE TITLE
阻止玩家饥饿

### ISSUE THREAD

**Issue by postyizhan** [Ez4p1xEL/NoBuildPlus#11]
您好！我在 https://github.com/Ez4p1xEL/NoBuildPlus/wiki/NoBuildPlus 和插件配置文件中没有找到 `hunger` 这种字眼，我希望 NoBuildPlus 可以阻止玩家饥饿

**Comment by Ez4p1xEL** [comment]
已在 NoBuildPlus 1.4.4 中添加，并于 Purpur 1.21.1 上测试可用。
