### ISSUE TITLE
无法禁止玩家放置物品展示框/画

### ISSUE THREAD

**Issue by ATCatBoss** [Ez4p1xEL/NoBuildPlus#13]
游戏版本1.20.2
插件版本1.4.9
使用paper核心

**Comment by ATCatBoss** [comment]
重新检测了一下，是无法禁止玩家放置荧光物品展示框，以及无法禁止玩家右键展示框后旋转展示框

**Comment by Ez4p1xEL** [comment]
有沒有在 flags.yml 的 frame 裏啓用 include-glow-frame

**Comment by ATCatBoss** [comment]
！  没有...

**Comment by Ez4p1xEL** [comment]
flags.yml裏 frame的 include-glow-frame 設置為 true, 然後再試試能否禁止放置熒光展示框。
至於你說的無法防止與展示框互動指的是普通展示框還是熒光展示框?

**Comment by ATCatBoss** [comment]
也是荧光的，include-glow-frame=true就没问题了，我粗心了

**Comment by Ez4p1xEL** [comment]
感謝反饋，已經在Wiki補充提示
