### ISSUE TITLE
1.21.1

### ISSUE THREAD

**Issue by Logan8642** [Ez4p1xEL/NoBuildPlus#7]
Please add support for 1.21.1

**Comment by Ez4p1xEL** [comment]
Any problem you met on 1.21.1? 
The recent updates were tested on 1.21.1 and they have no problem. 
Can you send the error logs?

**Comment by Logan8642** [comment]
I dont think there are any errors that I can see but I am using the latest version and I can't see the new flags.
![image](https://github.com/user-attachments/assets/c2be1e5e-1bb3-4f25-8d8b-c4554a4deb71)
![image](https://github.com/user-attachments/assets/691b5545-bf04-4905-b659-04f651d77591)

**Comment by Ez4p1xEL** [comment]
I think the problem is caused by missing flags in flags.yml.

NoBuildPlus still has not supported the auto update function for the configuration files.
You need to remove flags.yml and the language file and let them generate by themselves.

**Comment by Logan8642** [comment]
It worked thank you so much 🙏
